from transformers import AutoModelForCausalLM, AutoTokenizer

import torch
from torch.nn import Module
from typing import List, Tuple
import matplotlib.pyplot as plt
import time

# Import utility functions
from utilities import (
    max_fn,
    calculate_beta,
    calculate_alpha,
    plot_beta_histogram,
    print_accepted_tokens,
    crop_cache
)


@torch.no_grad()
def speculative_decoding(inputs, drafter, target, gamma=5, max_gen_len=40, eos_tokens_id=1, use_cache=False, return_betas=False):
    """
    Generate text sequence using the speculative decoding algorithm.
    Implementation of Speculative Decoding. (https://arxiv.org/pdf/2211.17192.pdf)
    
    Args:
        inputs (List[int]): input sequence of batch size 1.
        drafter (Module): drafter model.
        target (Module): target model.
        gamma (int): number of drafts generated by the drafter at each step.
        max_gen_len (int): maximum length of the generated sequence.
        eos_tokens_id (int or List[int]): end token id (could be multiple).
        use_cache (bool): whether to use cache.
        return_betas (bool): if True, return tuple of (generated_tokens, beta_analysis).
    
    Returns:
        List[int] or Tuple[List[int], List[dict]]: 
            - If return_betas=False: generated sequence (without the input prompt).
            - If return_betas=True: tuple of (generated_sequence, beta_analysis).
              beta_analysis is a list of dicts with keys:
                - 'beta' (float): acceptance probability for this position
                - 'sequence' (list): token sequence up to this position
                - 'position' (int): position in the sequence
                - 'accepted' (bool): whether this token was actually accepted
        
    Note: This generation methods only works for decoder-only models.
    """
    
    # Start timing
    start_time = time.time()
    
    drafter_cache, target_cache = None, None

    list_tokens_id = eos_tokens_id if isinstance(eos_tokens_id, list) else [eos_tokens_id]
    stop_tokens = torch.tensor(list_tokens_id, dtype=torch.long, device=target.device).unsqueeze(1)
    
    vocabulary_size = target.config.vocab_size    
        
    prompt_len = len(inputs)
    input_ids = torch.tensor([inputs], dtype=torch.long, device=target.device)  # shape: (1, prompt_len)
    
    max_seq_length = target.config.max_position_embeddings if hasattr(target.config, 'max_position_embeddings') else (target.config.max_context_length if hasattr(target.config, 'max_context_length') else 1024)
    max_total_len = min(max_seq_length, prompt_len + max_gen_len)
    
    tokens_generated = 0
    
    # Store beta analysis data as list of tuples: (beta_value, sequence_ids, position)
    beta_analysis = []
    
    while tokens_generated < max_gen_len:
        current_len = input_ids.shape[1]
        
        # Check if we've hit the model's max length
        if current_len >= max_total_len:
            break
            
        floored_gamma = min(gamma, max_total_len - current_len - 1)
        if floored_gamma == 0:
            break
            
        q = torch.zeros((1, floored_gamma, vocabulary_size), device=target.device)
        draft_tokens = []
                
        # Generate gamma drafts
        for k in range(floored_gamma):
            Mq = drafter(input_ids=input_ids, past_key_values=drafter_cache, use_cache=use_cache)
            drafter_cache = Mq.past_key_values
            draft_logits = Mq.logits[..., -1, :]
            draft_probs = torch.softmax(draft_logits, dim=-1)
            q[0, k] = draft_probs.to(target.device)
            x_q = torch.multinomial(draft_probs, num_samples=1).squeeze(-1)
            draft_tokens.append(x_q)
        # Append the draft token to input_ids
        input_ids = torch.cat([input_ids, torch.stack(draft_tokens, dim=1)], dim=1)
        
        # Run target model on all tokens including drafts
        Mp = target(input_ids=input_ids, past_key_values=target_cache, use_cache=use_cache)
        target_cache = Mp.past_key_values
        # Get logits for positions corresponding to the drafts
        draft_logits = Mp.logits[..., current_len - 1:-1, :]  # [1, corrected_gamma, vocab_size]
        p = torch.softmax(draft_logits, dim=-1)
        
        # Calculate acceptance probabilities for analysis (before rejection sampling)
        beta_start_idx = len(beta_analysis) if return_betas else 0
        if return_betas:
            betas = calculate_beta(p, q)  # Shape: (1, floored_gamma)
            for i, beta in enumerate(betas[0]):
                beta_analysis.append({
                    'beta': beta.item(),
                    'sequence': input_ids[0, max(0, current_len-10):current_len + i + 1].tolist(),
                    'position': current_len + i,
                    'accepted': False  # Will update after rejection sampling
                }) 
        
        # Compute the last accepted draft position (rejection sampling)
        r = torch.rand(floored_gamma, device=target.device)
        fractions = p / q
        n = floored_gamma
        for i in range(floored_gamma):
            if r[i] > fractions[0, i, input_ids[0, current_len + i]]:
                n = i
                break
        
        # Mark accepted tokens in beta_analysis (after we know n)
        if return_betas:
            for i in range(n):
                beta_analysis[beta_start_idx + i]['accepted'] = True
        
        
        
        # Trim input_ids to remove rejected tokens
        input_ids = input_ids[..., :current_len + n]

        # Check if the end token is in the accepted drafts
        accepted_tokens = input_ids[..., current_len:current_len + n]
        stop_locations = torch.nonzero(torch.eq(accepted_tokens, stop_tokens))
        if stop_locations.shape[0] > 0:
            stop_location = stop_locations[0, 1].item()
            # Trim to the stop location
            input_ids = input_ids[..., :current_len + stop_location + 1]
            result = input_ids[0, prompt_len:].tolist()
            
            # Calculate timing
            end_time = time.time()
            total_time = end_time - start_time
            
            if return_betas:
                return result, beta_analysis, total_time
            else:
                return result, total_time

        # Adjust the distribution and sample one more token
        if n == floored_gamma:
            # All drafts accepted, sample one more token
            p_p = Mp.logits[..., -1, :]
            p_p = torch.softmax(p_p, dim=-1)
            x = torch.multinomial(p_p, num_samples=1).squeeze(-1)
            # Keep all draft tokens and append the new token
            input_ids = torch.cat([input_ids, x.unsqueeze(0)], dim=1)
            tokens_generated += floored_gamma + 1
        else:
            # Some drafts rejected, trim to accepted tokens
            num_rejected = floored_gamma - n
            # Prune the cache for rejected tokens
            if use_cache:
                drafter_cache = crop_cache(drafter_cache, num_rejected)
                target_cache = crop_cache(target_cache, num_rejected + 1)
            # Sample a new token from adjusted distribution
            p_p = max_fn(p[..., n, :] - q[0, n, :])
            x = torch.multinomial(p_p, num_samples=1).squeeze(-1)
            input_ids = torch.cat([input_ids, x.unsqueeze(0)], dim=1)
            tokens_generated += n + 1
        
        # Check if we just generated an EOS token
        if torch.isin(input_ids[0, -1], stop_tokens):
            result = input_ids[0, prompt_len:].tolist()
            
            # Calculate timing
            end_time = time.time()
            total_time = end_time - start_time
            
            if return_betas:
                return result, beta_analysis, total_time
            else:
                return result, total_time
    
    result = input_ids[0, prompt_len:].tolist()
    
    # Calculate timing
    end_time = time.time()
    total_time = end_time - start_time
    
    if return_betas:
        return result, beta_analysis, total_time
    else:
        return result, total_time

def main():
    # Set manual seed for reproducibility
    device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
    torch.manual_seed(10)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(42)
    
    draft_model_name = "gpt2"
    target_model_name = "gpt2-xl"
    draft_model = AutoModelForCausalLM.from_pretrained(draft_model_name).to(device)
    target_model = AutoModelForCausalLM.from_pretrained(target_model_name).to(device)
    tokenizer = AutoTokenizer.from_pretrained(draft_model_name)
    input_text = "The United"
    input_ids = tokenizer.encode(input_text, return_tensors="pt").to(device)
    max_length = 15
    
    # Convert tensor to list of token ids
    inputs_list = input_ids[0].tolist()
    
    generated, beta_analysis, total_time = speculative_decoding(
        inputs=inputs_list,
        drafter=draft_model,
        target=target_model,
        gamma=5,
        max_gen_len=max_length,
        eos_tokens_id=tokenizer.eos_token_id,
        use_cache=True,
        return_betas=True
    )
    print(f"Decoded text: {input_text + ' ' + tokenizer.decode(generated, skip_special_tokens=True)}")
    
    # Display timing information
    print(f"\nTiming Information:")
    print(f"Total time: {total_time:.4f} seconds")
    print(f"Seconds per token: {total_time / len(generated):.4f}")
    # Calculate and display alpha
    alpha = calculate_alpha(beta_analysis, only_accepted=True)
    print(f"\nAlpha (α) = {alpha:.4f}")
    print(f"Number of beta measurements: {len(beta_analysis)}")
    print(f"Number of accepted tokens: {sum(1 for x in beta_analysis if x['accepted'])}")
    
    # Print tokens with their beta values and sequences
    print("\n" + "="*100)
    print("TOKEN ANALYSIS")
    print("="*100 + "\n")
    
    # Show all accepted tokens sorted by position
    print_accepted_tokens(beta_analysis, tokenizer=tokenizer, sort_by='position', acceptOrReject='both')
    
 
    # Plot beta distribution
    fig, ax = plot_beta_histogram(beta_analysis, only_accepted=True, save_path='experiments/results/beta_accepted.png')
    if fig:
        plt.show()
        # Optionally save: plot_beta_histogram(beta_analysis, only_accepted=True, save_path='beta_histogram.png')
    # Plot beta distribution
    fig, ax = plot_beta_histogram(beta_analysis, only_accepted=False, save_path='experiments/results/beta_all.png')
    if fig:
        plt.show()

if __name__ == "__main__":
    main()