from transformers import AutoModelForCausalLM, AutoTokenizer

import torch
from torch.nn import Module
from typing import List, Tuple
import matplotlib.pyplot as plt
import numpy as np
import time


def max_fn(x: torch.Tensor) -> torch.Tensor:
    """
    Max function.
        x: input tensor.
    Returns:
        tensor norm(max(0, x)).
    """
    x_max = torch.where(x > 0, x, torch.zeros_like(x))
    x_max_sum = torch.sum(x_max, dim=-1, keepdim=True)
    return x_max / x_max_sum

def calculate_beta(p, q):
    """
    shape of p and q: (1, floored_gamma, vocabulary_size)
    Calculate the beta parameter for the speculative decoding algorithm.
    Returns:
        Tensor of shape (1, floored_gamma)
    """
    return torch.sum(torch.min(p, q), dim=-1) 


def calculate_alpha(beta_analysis, only_accepted=True):
    """
    Calculate alpha (α) - the expected acceptance rate across many tokens.
    α = E[β] = 1 - E[D_KL(p, q)]
    
    Args:
        beta_analysis: List of dicts with 'beta' and 'accepted' keys
        only_accepted: If True, only include β values for accepted tokens (recommended).
                      If False, include all β values regardless of acceptance.
    
    Returns:
        float: α value (average acceptance probability)
    
    Note: The paper measures α on "10K tokens generated by Mp", suggesting
          only_accepted=True is the intended interpretation.
    """
    if not beta_analysis:
        return 0.0
    
    if only_accepted:
        # Only include β values where the token was actually accepted
        betas = [entry['beta'] for entry in beta_analysis if entry.get('accepted', False)]
    else:
        # Include all β values (theoretical agreement measure)
        betas = [entry['beta'] for entry in beta_analysis]
    
    if not betas:
        return 0.0
    
    alpha = sum(betas) / len(betas)
    return alpha


def plot_beta_histogram(beta_analysis, only_accepted=True, title=None, save_path=None):
    """
    Plot a histogram of beta values with 0.1 interval bins.
    
    Args:
        beta_analysis: List of dicts with 'beta' and 'accepted' keys
        only_accepted: If True, only plot β values for accepted tokens
        title: Optional custom title for the plot
        save_path: Optional path to save the figure (e.g., 'beta_hist.png')
    
    Returns:
        tuple: (fig, ax) matplotlib figure and axis objects
    """
    # Extract beta values
    if only_accepted:
        betas = [entry['beta'] for entry in beta_analysis if entry.get('accepted', False)]
        default_title = 'Beta Distribution (Accepted Tokens Only)'
    else:
        betas = [entry['beta'] for entry in beta_analysis]
        default_title = 'Beta Distribution (All Draft Positions)'
    
    if not betas:
        print("No beta values to plot!")
        return None, None
    
    # Create bins at 0.1 intervals: [0.0, 0.1), [0.1, 0.2), ..., [0.9, 1.0]
    bins = np.arange(0.0, 1.1, 0.1)
    
    # Create figure
    fig, ax = plt.subplots(figsize=(10, 6))
    
    # Plot histogram
    counts, bin_edges, patches = ax.hist(betas, bins=bins, edgecolor='black', alpha=0.7, color='steelblue')
    
    # Add labels and title
    ax.set_xlabel('Beta (β) - Acceptance Probability', fontsize=12)
    ax.set_ylabel('Frequency', fontsize=12)
    ax.set_title(title if title else default_title, fontsize=14, fontweight='bold')
    ax.set_xticks(bins)
    ax.grid(axis='y', alpha=0.3, linestyle='--')
    
    # Add statistics text box
    alpha_value = sum(betas) / len(betas)
    stats_text = f'α = {alpha_value:.4f}\nN = {len(betas)}\nMin = {min(betas):.4f}\nMax = {max(betas):.4f}'
    ax.text(0.02, 0.98, stats_text, transform=ax.transAxes, 
            verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5),
            fontsize=10, family='monospace')
    
    # Add percentage labels on top of bars
    for count, edge in zip(counts, bin_edges[:-1]):
        if count > 0:
            percentage = 100 * count / len(betas)
            ax.text(edge + 0.05, count, f'{percentage:.1f}%', 
                   ha='center', va='bottom', fontsize=9)
    
    plt.tight_layout()
    
    # Save if path provided
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"Figure saved to {save_path}")
    
    return fig, ax


def print_accepted_tokens(beta_analysis, tokenizer=None, sort_by='position', top_n=None, save_path=None, acceptOrReject='accepted'):
    """
    Display accepted or rejected tokens with their beta values and sequences.
    
    Args:
        beta_analysis: List of dicts with 'beta', 'sequence', 'position', and 'accepted' keys
        tokenizer: Optional tokenizer to decode sequences to text
        sort_by: Sort order - 'position' (default), 'beta_asc', 'beta_desc'
        top_n: Only show top N entries (after sorting)
        save_path: Optional path to save output to a file (e.g., 'accepted_tokens.txt')
        acceptOrReject: Filter tokens - 'accepted' (default), 'rejected', or 'both'
    
    Returns:
        list: Filtered and sorted list of token entries
    """
    # Filter based on acceptOrReject parameter
    if acceptOrReject == 'accepted':
        filtered = [entry for entry in beta_analysis if entry.get('accepted', False)]
        title = "ACCEPTED TOKENS"
    elif acceptOrReject == 'rejected':
        filtered = [entry for entry in beta_analysis if not entry.get('accepted', False)]
        title = "REJECTED TOKENS"
    elif acceptOrReject == 'both':
        filtered = beta_analysis
        title = "ALL TOKENS (ACCEPTED & REJECTED)"
    else:
        raise ValueError(f"acceptOrReject must be 'accepted', 'rejected', or 'both', got '{acceptOrReject}'")
    
    if not filtered:
        print(f"No {acceptOrReject} tokens found!")
        return []
    
    # Sort based on specified order
    if sort_by == 'beta_desc':
        filtered_sorted = sorted(filtered, key=lambda x: x['beta'], reverse=True)
    elif sort_by == 'beta_asc':
        filtered_sorted = sorted(filtered, key=lambda x: x['beta'])
    else:  # 'position'
        filtered_sorted = sorted(filtered, key=lambda x: x['position'])
    
    # Limit to top_n if specified
    if top_n:
        filtered_sorted = filtered_sorted[:top_n]
    
    # Prepare output
    output_lines = []
    output_lines.append("=" * 100)
    output_lines.append(f"{title} ANALYSIS (Total: {len(filtered)}, Showing: {len(filtered_sorted)})")
    output_lines.append(f"Sort by: {sort_by}")
    output_lines.append("=" * 100)
    output_lines.append("")
    
    for i, entry in enumerate(filtered_sorted, 1):
        beta = entry['beta']
        position = entry['position']
        sequence = entry['sequence']
        status = "✓ ACCEPTED" if entry.get('accepted', False) else "✗ REJECTED"
        
        output_lines.append(f"[{i}] Position: {position:4d} | Beta: {beta:.4f} | Status: {status}")
        output_lines.append(f"    Token IDs: {sequence}")
        
        # Decode if tokenizer provided
        if tokenizer:
            try:
                decoded = tokenizer.decode(sequence, skip_special_tokens=False)
                output_lines.append(f"    Text: '{decoded}'")
            except Exception as e:
                output_lines.append(f"    Text: <decode error: {e}>")
        
        output_lines.append("")
    
    
    # Join and print
    output_text = "\n".join(output_lines)
    print(output_text)
    
    # Save to file if requested
    if save_path:
        with open(save_path, 'w', encoding='utf-8') as f:
            f.write(output_text)
        print(f"\nOutput saved to {save_path}")
    
    return filtered_sorted


def crop_cache(cache, num_tokens_to_prune: int):
    """
    Crop the cache by removing the specified number of tokens from the end.
    Supports both tuple cache (older format) and DynamicCache (newer format).
    
    Args:
        cache: The KV cache to be pruned (tuple or DynamicCache).
        num_tokens_to_prune (int): The number of tokens to discard from the end.
    
    Returns:
        The pruned KV cache.
    """
    if cache is None:
        return None
    
    if isinstance(cache, tuple):
        # Tuple cache: tuple of (key, value) pairs for each layer
        return tuple(
            (k[:, :, :-num_tokens_to_prune, :], v[:, :, :-num_tokens_to_prune, :])
            for k, v in cache
        )
    else:
        # DynamicCache: crop to keep first (current_length - num_to_prune) tokens
        current_length = cache.get_seq_length()
        cache.crop(current_length - num_tokens_to_prune)
        return cache


@torch.no_grad()
def speculative_decoding(inputs, drafter, target, gamma=5, max_gen_len=40, eos_tokens_id=1, use_cache=False, return_betas=False):
    """
    Generate text sequence using the speculative decoding algorithm.
    Implementation of Speculative Decoding. (https://arxiv.org/pdf/2211.17192.pdf)
    
    Args:
        inputs (List[int]): input sequence of batch size 1.
        drafter (Module): drafter model.
        target (Module): target model.
        gamma (int): number of drafts generated by the drafter at each step.
        max_gen_len (int): maximum length of the generated sequence.
        eos_tokens_id (int or List[int]): end token id (could be multiple).
        use_cache (bool): whether to use cache.
        return_betas (bool): if True, return tuple of (generated_tokens, beta_analysis).
    
    Returns:
        List[int] or Tuple[List[int], List[dict]]: 
            - If return_betas=False: generated sequence (without the input prompt).
            - If return_betas=True: tuple of (generated_sequence, beta_analysis).
              beta_analysis is a list of dicts with keys:
                - 'beta' (float): acceptance probability for this position
                - 'sequence' (list): token sequence up to this position
                - 'position' (int): position in the sequence
                - 'accepted' (bool): whether this token was actually accepted
        
    Note: This generation methods only works for decoder-only models.
    """
    
    # Start timing
    start_time = time.time()
    
    drafter_cache, target_cache = None, None

    list_tokens_id = eos_tokens_id if isinstance(eos_tokens_id, list) else [eos_tokens_id]
    stop_tokens = torch.tensor(list_tokens_id, dtype=torch.long, device=target.device).unsqueeze(1)
    
    vocabulary_size = target.config.vocab_size    
        
    prompt_len = len(inputs)
    input_ids = torch.tensor([inputs], dtype=torch.long, device=target.device)  # shape: (1, prompt_len)
    
    max_seq_length = target.config.max_position_embeddings if hasattr(target.config, 'max_position_embeddings') else (target.config.max_context_length if hasattr(target.config, 'max_context_length') else 1024)
    max_total_len = min(max_seq_length, prompt_len + max_gen_len)
    
    tokens_generated = 0
    
    # Store beta analysis data as list of tuples: (beta_value, sequence_ids, position)
    beta_analysis = []
    
    while tokens_generated < max_gen_len:
        current_len = input_ids.shape[1]
        
        # Check if we've hit the model's max length
        if current_len >= max_total_len:
            break
            
        floored_gamma = min(gamma, max_total_len - current_len - 1)
        if floored_gamma == 0:
            break
            
        q = torch.zeros((1, floored_gamma, vocabulary_size), device=target.device)
        draft_tokens = []
                
        # Generate gamma drafts
        for k in range(floored_gamma):
            Mq = drafter(input_ids=input_ids, past_key_values=drafter_cache, use_cache=use_cache)
            drafter_cache = Mq.past_key_values
            draft_logits = Mq.logits[..., -1, :]
            draft_probs = torch.softmax(draft_logits, dim=-1)
            q[0, k] = draft_probs.to(target.device)
            x_q = torch.multinomial(draft_probs, num_samples=1).squeeze(-1)
            draft_tokens.append(x_q)
        # Append the draft token to input_ids
        input_ids = torch.cat([input_ids, torch.stack(draft_tokens, dim=1)], dim=1)
        
        # Run target model on all tokens including drafts
        Mp = target(input_ids=input_ids, past_key_values=target_cache, use_cache=use_cache)
        target_cache = Mp.past_key_values
        # Get logits for positions corresponding to the drafts
        draft_logits = Mp.logits[..., current_len - 1:-1, :]  # [1, corrected_gamma, vocab_size]
        p = torch.softmax(draft_logits, dim=-1)
        
        # Calculate acceptance probabilities for analysis (before rejection sampling)
        beta_start_idx = len(beta_analysis) if return_betas else 0
        if return_betas:
            betas = calculate_beta(p, q)  # Shape: (1, floored_gamma)
            for i, beta in enumerate(betas[0]):
                beta_analysis.append({
                    'beta': beta.item(),
                    'sequence': input_ids[0, max(0, current_len-10):current_len + i + 1].tolist(),
                    'position': current_len + i,
                    'accepted': False  # Will update after rejection sampling
                }) 
        
        # Compute the last accepted draft position (rejection sampling)
        r = torch.rand(floored_gamma, device=target.device)
        fractions = p / q
        n = floored_gamma
        for i in range(floored_gamma):
            if r[i] > fractions[0, i, input_ids[0, current_len + i]]:
                n = i
                break
        
        # Mark accepted tokens in beta_analysis (after we know n)
        if return_betas:
            for i in range(n):
                beta_analysis[beta_start_idx + i]['accepted'] = True
        
        
        
        # Trim input_ids to remove rejected tokens
        input_ids = input_ids[..., :current_len + n]

        # Check if the end token is in the accepted drafts
        accepted_tokens = input_ids[..., current_len:current_len + n]
        stop_locations = torch.nonzero(torch.eq(accepted_tokens, stop_tokens))
        if stop_locations.shape[0] > 0:
            stop_location = stop_locations[0, 1].item()
            # Trim to the stop location
            input_ids = input_ids[..., :current_len + stop_location + 1]
            result = input_ids[0, prompt_len:].tolist()
            
            # Calculate timing
            end_time = time.time()
            total_time = end_time - start_time
            
            if return_betas:
                return result, beta_analysis, total_time
            else:
                return result, total_time

        # Adjust the distribution and sample one more token
        if n == floored_gamma:
            # All drafts accepted, sample one more token
            p_p = Mp.logits[..., -1, :]
            p_p = torch.softmax(p_p, dim=-1)
            x = torch.multinomial(p_p, num_samples=1).squeeze(-1)
            # Keep all draft tokens and append the new token
            input_ids = torch.cat([input_ids, x.unsqueeze(0)], dim=1)
            tokens_generated += floored_gamma + 1
        else:
            # Some drafts rejected, trim to accepted tokens
            num_rejected = floored_gamma - n
            # Prune the cache for rejected tokens
            if use_cache:
                drafter_cache = crop_cache(drafter_cache, num_rejected)
                target_cache = crop_cache(target_cache, num_rejected + 1)
            # Sample a new token from adjusted distribution
            p_p = max_fn(p[..., n, :] - q[0, n, :])
            x = torch.multinomial(p_p, num_samples=1).squeeze(-1)
            input_ids = torch.cat([input_ids, x.unsqueeze(0)], dim=1)
            tokens_generated += n + 1
        
        # Check if we just generated an EOS token
        if torch.isin(input_ids[0, -1], stop_tokens):
            result = input_ids[0, prompt_len:].tolist()
            
            # Calculate timing
            end_time = time.time()
            total_time = end_time - start_time
            
            if return_betas:
                return result, beta_analysis, total_time
            else:
                return result, total_time
    
    result = input_ids[0, prompt_len:].tolist()
    
    # Calculate timing
    end_time = time.time()
    total_time = end_time - start_time
    
    if return_betas:
        return result, beta_analysis, total_time
    else:
        return result, total_time

def main():
    # Set manual seed for reproducibility
    device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
    torch.manual_seed(10)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(42)
    
    draft_model_name = "gpt2"
    target_model_name = "gpt2-xl"
    draft_model = AutoModelForCausalLM.from_pretrained(draft_model_name).to(device)
    target_model = AutoModelForCausalLM.from_pretrained(target_model_name).to(device)
    tokenizer = AutoTokenizer.from_pretrained(draft_model_name)
    input_text = "The United"
    input_ids = tokenizer.encode(input_text, return_tensors="pt").to(device)
    max_length = 15
    
    # Convert tensor to list of token ids
    inputs_list = input_ids[0].tolist()
    
    generated, beta_analysis, total_time = speculative_decoding(
        inputs=inputs_list,
        drafter=draft_model,
        target=target_model,
        gamma=5,
        max_gen_len=max_length,
        eos_tokens_id=tokenizer.eos_token_id,
        use_cache=True,
        return_betas=True
    )
    print(f"Decoded text: {input_text + ' ' + tokenizer.decode(generated, skip_special_tokens=True)}")
    
    # Display timing information
    print(f"\nTiming Information:")
    print(f"Total time: {total_time:.4f} seconds")
    print(f"Seconds per token: {total_time / len(generated):.4f}")
    # Calculate and display alpha
    alpha = calculate_alpha(beta_analysis, only_accepted=True)
    print(f"\nAlpha (α) = {alpha:.4f}")
    print(f"Number of beta measurements: {len(beta_analysis)}")
    print(f"Number of accepted tokens: {sum(1 for x in beta_analysis if x['accepted'])}")
    
    # Print tokens with their beta values and sequences
    print("\n" + "="*100)
    print("TOKEN ANALYSIS")
    print("="*100 + "\n")
    
    # Show all accepted tokens sorted by position
    print_accepted_tokens(beta_analysis, tokenizer=tokenizer, sort_by='position', acceptOrReject='both')
    
 
    # Plot beta distribution
    fig, ax = plot_beta_histogram(beta_analysis, only_accepted=True)
    if fig:
        plt.show()
        # Optionally save: plot_beta_histogram(beta_analysis, only_accepted=True, save_path='beta_histogram.png')
    
if __name__ == "__main__":
    main()