import torch
import matplotlib.pyplot as plt
import numpy as np


def max_fn(x: torch.Tensor) -> torch.Tensor:
    """
    Max function.
        x: input tensor.
    Returns:
        tensor norm(max(0, x)).
    """
    x_max = torch.where(x > 0, x, torch.zeros_like(x))
    x_max_sum = torch.sum(x_max, dim=-1, keepdim=True)
    return x_max / x_max_sum


def calculate_beta(p, q):
    """
    shape of p and q: (1, floored_gamma, vocabulary_size)
    Calculate the beta parameter for the speculative decoding algorithm.
    Returns:
        Tensor of shape (1, floored_gamma)
    """
    return torch.sum(torch.min(p, q), dim=-1) 


def calculate_alpha(beta_analysis, only_accepted=True):
    """
    Calculate alpha (α) - the expected acceptance rate across many tokens.
    α = E[β] = 1 - E[D_KL(p, q)]
    
    Args:
        beta_analysis: List of dicts with 'beta' and 'accepted' keys
        only_accepted: If True, only include β values for accepted tokens (recommended).
                      If False, include all β values regardless of acceptance.
    
    Returns:
        float: α value (average acceptance probability)
    
    Note: The paper measures α on "10K tokens generated by Mp", suggesting
          only_accepted=True is the intended interpretation.
    """
    if not beta_analysis:
        return 0.0
    
    if only_accepted:
        # Only include β values where the token was actually accepted
        betas = [entry['beta'] for entry in beta_analysis if entry.get('accepted', False)]
    else:
        # Include all β values (theoretical agreement measure)
        betas = [entry['beta'] for entry in beta_analysis]
    
    if not betas:
        return 0.0
    
    alpha = sum(betas) / len(betas)
    return alpha


def plot_beta_histogram(beta_analysis, only_accepted=True, title=None, save_path=None):
    """
    Plot a histogram of beta values with 0.1 interval bins.
    
    Args:
        beta_analysis: List of dicts with 'beta' and 'accepted' keys
        only_accepted: If True, only plot β values for accepted tokens
        title: Optional custom title for the plot
        save_path: Optional path to save the figure (e.g., 'beta_hist.png')
    
    Returns:
        tuple: (fig, ax) matplotlib figure and axis objects
    """
    # Extract beta values
    if only_accepted:
        betas = [entry['beta'] for entry in beta_analysis if entry.get('accepted', False)]
        default_title = 'Beta Distribution (Accepted Tokens Only)'
    else:
        betas = [entry['beta'] for entry in beta_analysis]
        default_title = 'Beta Distribution (All Draft Positions)'
    
    if not betas:
        print("No beta values to plot!")
        return None, None
    
    # Create bins at 0.1 intervals: [0.0, 0.1), [0.1, 0.2), ..., [0.9, 1.0]
    bins = np.arange(0.0, 1.1, 0.1)
    
    # Create figure
    fig, ax = plt.subplots(figsize=(10, 6))
    
    # Plot histogram
    counts, bin_edges, patches = ax.hist(betas, bins=bins, edgecolor='black', alpha=0.7, color='steelblue')
    
    # Add labels and title
    ax.set_xlabel('Beta (β) - Acceptance Probability', fontsize=12)
    ax.set_ylabel('Frequency', fontsize=12)
    ax.set_title(title if title else default_title, fontsize=14, fontweight='bold')
    ax.set_xticks(bins)
    ax.grid(axis='y', alpha=0.3, linestyle='--')
    
    # Add statistics text box
    alpha_value = sum(betas) / len(betas)
    stats_text = f'α = {alpha_value:.4f}\nN = {len(betas)}\nMin = {min(betas):.4f}\nMax = {max(betas):.4f}'
    ax.text(0.02, 0.98, stats_text, transform=ax.transAxes, 
            verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5),
            fontsize=10, family='monospace')
    
    # Add percentage labels on top of bars
    for count, edge in zip(counts, bin_edges[:-1]):
        if count > 0:
            percentage = 100 * count / len(betas)
            ax.text(edge + 0.05, count, f'{percentage:.1f}%', 
                   ha='center', va='bottom', fontsize=9)
    
    plt.tight_layout()
    
    # Save if path provided
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"Figure saved to {save_path}")
    
    return fig, ax


def print_accepted_tokens(beta_analysis, tokenizer=None, sort_by='position', top_n=None, save_path=None, acceptOrReject='accepted'):
    """
    Display accepted or rejected tokens with their beta values and sequences.
    
    Args:
        beta_analysis: List of dicts with 'beta', 'sequence', 'position', and 'accepted' keys
        tokenizer: Optional tokenizer to decode sequences to text
        sort_by: Sort order - 'position' (default), 'beta_asc', 'beta_desc'
        top_n: Only show top N entries (after sorting)
        save_path: Optional path to save output to a file (e.g., 'accepted_tokens.txt')
        acceptOrReject: Filter tokens - 'accepted' (default), 'rejected', or 'both'
    
    Returns:
        list: Filtered and sorted list of token entries
    """
    # Filter based on acceptOrReject parameter
    if acceptOrReject == 'accepted':
        filtered = [entry for entry in beta_analysis if entry.get('accepted', False)]
        title = "ACCEPTED TOKENS"
    elif acceptOrReject == 'rejected':
        filtered = [entry for entry in beta_analysis if not entry.get('accepted', False)]
        title = "REJECTED TOKENS"
    elif acceptOrReject == 'both':
        filtered = beta_analysis
        title = "ALL TOKENS (ACCEPTED & REJECTED)"
    else:
        raise ValueError(f"acceptOrReject must be 'accepted', 'rejected', or 'both', got '{acceptOrReject}'")
    
    if not filtered:
        print(f"No {acceptOrReject} tokens found!")
        return []
    
    # Sort based on specified order
    if sort_by == 'beta_desc':
        filtered_sorted = sorted(filtered, key=lambda x: x['beta'], reverse=True)
    elif sort_by == 'beta_asc':
        filtered_sorted = sorted(filtered, key=lambda x: x['beta'])
    else:  # 'position'
        filtered_sorted = sorted(filtered, key=lambda x: x['position'])
    
    # Limit to top_n if specified
    if top_n:
        filtered_sorted = filtered_sorted[:top_n]
    
    # Prepare output
    output_lines = []
    output_lines.append("=" * 100)
    output_lines.append(f"{title} ANALYSIS (Total: {len(filtered)}, Showing: {len(filtered_sorted)})")
    output_lines.append(f"Sort by: {sort_by}")
    output_lines.append("=" * 100)
    output_lines.append("")
    
    for i, entry in enumerate(filtered_sorted, 1):
        beta = entry['beta']
        position = entry['position']
        sequence = entry['sequence']
        status = "✓ ACCEPTED" if entry.get('accepted', False) else "✗ REJECTED"
        
        output_lines.append(f"[{i}] Position: {position:4d} | Beta: {beta:.4f} | Status: {status}")
        output_lines.append(f"    Token IDs: {sequence}")
        
        # Decode if tokenizer provided
        if tokenizer:
            try:
                decoded = tokenizer.decode(sequence, skip_special_tokens=False)
                output_lines.append(f"    Text: '{decoded}'")
            except Exception as e:
                output_lines.append(f"    Text: <decode error: {e}>")
        
        output_lines.append("")
    
    
    # Join and print
    output_text = "\n".join(output_lines)
    print(output_text)
    
    # Save to file if requested
    if save_path:
        with open(save_path, 'w', encoding='utf-8') as f:
            f.write(output_text)
        print(f"\nOutput saved to {save_path}")
    
    return filtered_sorted


def crop_cache(cache, num_tokens_to_prune: int):
    """
    Crop the cache by removing the specified number of tokens from the end.
    Supports both tuple cache (older format) and DynamicCache (newer format).
    
    Args:
        cache: The KV cache to be pruned (tuple or DynamicCache).
        num_tokens_to_prune (int): The number of tokens to discard from the end.
    
    Returns:
        The pruned KV cache.
    """
    if cache is None:
        return None
    
    if isinstance(cache, tuple):
        # Tuple cache: tuple of (key, value) pairs for each layer
        return tuple(
            (k[:, :, :-num_tokens_to_prune, :], v[:, :, :-num_tokens_to_prune, :])
            for k, v in cache
        )
    else:
        # DynamicCache: crop to keep first (current_length - num_to_prune) tokens
        current_length = cache.get_seq_length()
        cache.crop(current_length - num_tokens_to_prune)
        return cache

